### ISSUE TITLE
Dashboard won't update

### ISSUE THREAD

**Issue by trideck** [aportela/spieldose#1]
In normal operation the dashboard only updates when the page is explicit reloaded.

Maybe a update button in the dashboard would do the trick.

Thanks in advance.

**Comment by aportela** [comment]
added refresh button [(d6f36e88fc6b2021ac483a5780e7ef669876240a)](https://github.com/aportela/spieldose/commit/d6f36e88fc6b2021ac483a5780e7ef669876240a)
