### ISSUE TITLE
How to insert a script in vue

### ISSUE THREAD

**Issue by popouille** [aportela/spieldose#10]
Hello,
I trying to insert this script in container.js after <spieldose-menu-component></spieldose-menu-component>

> <script id="cid0020000186643567170" data-cfasync="false" async src="//st.chatango.com/js/gz/emb.js" style="width: 400px;height: 600px;">{"handle":"***","arch":"js","styles":{"a":"CC0000","c":"000000","d":"000000","f":0,"h":"ffffff","i":0,"k":"CC0000","l":"dbdbdb","m":"CC0000","n":"FFFFFF","p":"10","q":"dbdbdb","fwtickm":1}}</script>

but i don't get it working

**Comment by aportela** [comment]
The script load declaration is done at the end of the body section in main twig template

https://github.com/aportela/spieldose/blob/master/templates/index.html.twig

**Comment by popouille** [comment]
Hello,

Yes, This is to put and load scripts globally, but i need to put this script in container.js to display the object after menu div.

I tried to put 

> <script id="cid0020000186643567170" data-cfasync="false" async src="//st.chatango.com/js/gz/emb.js" style="width: 400px;height: 600px;"></script>

in index.html.twig

then call the script on the good location by inserting:

> {"handle":"***","arch":"js","styles":{"a":"CC0000","c":"000000","d":"000000","f":0,"h":"ffffff","i":0,"k":"CC0000","l":"dbdbdb","m":"CC0000","n":"FFFFFF","p":"10","q":"dbdbdb","fwtickm":1}}

in container.js.

but it doesn't work

**Comment by aportela** [comment]
I do not think it's a good idea to insert a script that modifies the html elements of the template in the vuejs component due to how vuejs works. If you detail what it is that you intend to do, perhaps I can offer you another approach to the problem.

**Comment by popouille** [comment]
Hello,

this is just a online visitors counter:
https://whos.amung.us/

I want to put one to see who is online

**Comment by aportela** [comment]
Sorry, I do not know how you could integrate that code into the vue template. Try using another service of visitor counter that allows you to embed an html code directly, for example:

http://www.cutercounter.com/getcode.php?id=10641&nd=6&style=52

Many free services offer the possibility of embedding the html code directly through a link and an image, without javascript.

You just have to include that code (html) in the desired place of the template
