### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by popouille** [aportela/spieldose#11]
Hello,
Thi si possible to make a separate file for translations? and move all text to variable with this way we can update the script without overwriting the text each time.

thank you

**Comment by aportela** [comment]
I have pending (it is on the list of things to do) adding the plugin vue18n for internalization support but these days I am restructuring the code enough and while it is not finalized I will not start with new things.

**Comment by aportela** [comment]
done: check "common > locale" param on AppSettings.php and translations on path public/scripts/locale
