### ISSUE TITLE
Artist Details. Tracks. Page controls doesn't operates

### ISSUE THREAD

**Issue by trideck** [aportela/spieldose#3]
When the track list of a artist have several pages, none of the page controls have effect.

Clicking in the page numbers or in the "Previous" / "Next" buttons don't change the results.

Thanks in advance.

**Comment by trideck** [comment]
It continues failing.

**Comment by aportela** [comment]
[enabled pagination & changed routes](https://github.com/aportela/spieldose/commit/910db811131474ceec722c295bb4988474f6aab7)

TODO: filter by text on all fields

**Comment by aportela** [comment]
the problem was not related with pagination but results enconding, also fixed in

https://github.com/aportela/spieldose/commit/2e462563625b169c804fa4c20084093db0f4625b
