### ISSUE TITLE
Override sass style

### ISSUE THREAD

**Issue by popouille** [aportela/spieldose#9]
Hello,

How to override (or edit) a sass style directive?

i want to edit or override this one in hero.sass:
.hero.is-light.is-bold {
    /* background-image: linear-gradient(141deg, #dfd8d9 0%, whitesmoke 71%, white 100%); */
}

i tried to put in app.css, but it didn't override the sass.

**Comment by aportela** [comment]
if you want to disable (override) the background of this class use the important statement in the custom-style of app.css

.hero.is-light.is-bold {
/* background-image: linear-gradient(141deg, #dfd8d9 0%, whitesmoke 71%, white 100%); */
background: none ! important;
}

**Comment by popouille** [comment]
i already tried in app.css, but it keeping default directive of the sass file ! 
! important or not.
That why i looking to edit this directly on sass, but i don't know how it works, as there don't have any sass file in public/vendor/bulma

**Comment by aportela** [comment]
I don't use/customize the sass, I referecenced the original bulma dist css. If you made any changes I think that you need recompile sass onto new bulma.css

By the way, the customized rule on my app.css works fine

.hero.is-light.is-bold
{
    background: none !important;
}

If I put this on app.css background gradient is disabled

This is not a spieldose issue but a problem of understanding and modifying style sheets
